  File "C:\projects\GreatPianoService\GreatPSproj\GreatPSapp\models.py", line 9, in Piano
    ('grand','Grand'),
TypeError: 'str' object is not callable
(PianoService) PS C:\projects\GreatPianoService\GreatPSproj> python manage.py makemigrations GreatPSapp
SystemCheckError: System check identified some issues:

ERRORS:
GreatPSapp.Piano.serial_num: (fields.E120) CharFields must define a 'max_length' attribute.
(PianoService) PS C:\projects\GreatPianoService\GreatPSproj> python manage.py makemigrations GreatPSapp
You are trying to change the nullable field 'serial_num' on piano to non-nullable without a default; we can't do that (t
he database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL opera
tion to handle NULL values in a previous data migration)
 3) Quit, and let me add a default in models.py
Select an option: 2
Migrations for 'GreatPSapp':
  GreatPSapp\migrations\0005_auto_20170718_2123.py
    - Alter field mod on piano
    - Alter field serial_num on piano
(PianoService) PS C:\projects\GreatPianoService\GreatPSproj> python manage.py migrate GreatPSapp
Operations to perform:
  Apply all migrations: GreatPSapp
Running migrations:
  Applying GreatPSapp.0005_auto_20170718_2123... OK
(PianoService) PS C:\projects\GreatPianoService\GreatPSproj> python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
July 18, 2017 - 21:24:23
Django version 1.11.3, using settings 'GreatPSproj.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CTRL-BREAK.
(PianoService) PS C:\projects\GreatPianoService\GreatPSproj> python manage.py makemigrations GreatPSapp
No changes detected in app 'GreatPSapp'
(PianoService) PS C:\projects\GreatPianoService\GreatPSproj>